# Generated by Django 5.0 on 2023-12-07 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AUTOMATED_AUDIT', 'Automated Audit'), ('DATA_CLASSIFICATION', 'Data Classification'), ('TPA_REGULAR_CHECK', 'TPA Regular Check'), ('DYNAMIC_DATA_OPERATION', 'Dynamic Data Operation'), ('RISK_ASSESSMENT', 'Risk Assessment'), ('USER_COLLABORATION', 'User Collaboration'), ('INFO_MANAGEMENT', 'Information Management'), ('SYSTEM_EFFICIENCY', 'System Efficiency'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('SECURITY_INCIDENT', 'Security Incident Investigation'), ('DATA_BACKUP_RESTORE', 'Data Backup and Restore'), ('ACCESS_GRANT_REVOKE', 'Access Grant/Revoke'), ('AUDIT_REPORT_GENERATION', 'Audit Report Generation'), ('SYSTEM_UPGRADE', 'System Upgrade'), ('EXTERNAL_SYSTEM_INTEGRATION', 'External System Integration')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('related_object', models.CharField(choices=[('USER_ACCOUNT', 'User Account'), ('FINANCIAL_TRANSACTION', 'Financial Transaction'), ('DATA_RECORD', 'Data Record'), ('DATABASE_TABLE', 'Database Table'), ('SYSTEM_SETTING', 'System Setting'), ('DOCUMENT', 'Document'), ('SECURITY_POLICY', 'Security Policy'), ('APPLICATION', 'Application'), ('NETWORK_DEVICE', 'Network Device'), ('EMPLOYEE_RECORD', 'Employee Record'), ('VENDOR_CONTRACT', 'Vendor Contract'), ('CLIENT_RECORD', 'Client Record'), ('PROJECT', 'Project'), ('SERVICE_REQUEST', 'Service Request'), ('AUDIT_LOG_ENTRY', 'Audit Log Entry')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
