# Generated by Django 5.0 on 2023-12-07 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial Risk'), ('OPERATIONAL', 'Operational Risk'), ('COMPLIANCE', 'Compliance Risk'), ('STRATEGIC', 'Strategic Risk')], max_length=20)),
                ('description', models.TextField()),
                ('impact', models.CharField(max_length=255)),
                ('likelihood', models.CharField(max_length=255)),
                ('mitigation_plan', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
